// <auto-generated />
using System;
using Infrastructures.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api_scm.Migrations
{
    [DbContext(typeof(ScmDbContext))]
    [Migration("20260901045247_AddApprovalEngineAndPurchaseRequisitions")]
    partial class AddApprovalEngineAndPurchaseRequisitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domains.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("ApprovalRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalRequestId"));

                    b.Property<DateTime?>("ActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ApproverId")
                        .HasColumnType("text");

                    b.Property<string>("ApproverName")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalRequestId");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_ApprovalRequests_RequestedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ApprovalRequests_Status");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_ApprovalRequests_Entity");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("Domains.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domains.Entities.BatchConsumption", b =>
                {
                    b.Property<int>("BatchConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchConsumptionId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequiredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("SourceSupplierId")
                        .HasColumnType("integer");

                    b.HasKey("BatchConsumptionId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SourceSupplierId");

                    b.ToTable("BatchConsumptions");
                });

            modelBuilder.Entity("Domains.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domains.Entities.DocumentSequence", b =>
                {
                    b.Property<int>("DocumentSequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentSequenceId"));

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("DocumentSequenceId");

                    b.HasIndex("DocType", "Year")
                        .IsUnique();

                    b.ToTable("DocumentSequences");
                });

            modelBuilder.Entity("Domains.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Domains.Entities.FinishedProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("ItemId");

                    b.ToTable("FinishedProducts");
                });

            modelBuilder.Entity("Domains.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("InventoryId");

                    b.HasIndex("DriverId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ItemId", "LocationId")
                        .IsUnique();

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventories_CurrentStock_NotNegative", "\"CurrentStock\" >= 0");
                        });
                });

            modelBuilder.Entity("Domains.Entities.InventoryLot", b =>
                {
                    b.Property<int>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LotId"));

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int?>("GrnLineId")
                        .HasColumnType("integer");

                    b.Property<string>("HoldReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsExpiryEstimated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpeningBalance")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("QuantityRemaining")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierLotNo")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("UomId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("LotId");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_InventoryLots_ExpiryDate");

                    b.HasIndex("LocationId");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("IX_InventoryLots_SupplierId");

                    b.HasIndex("UomId");

                    b.HasIndex("LotCode", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryLots_LotCode_LocationId");

                    b.HasIndex("ItemId", "LocationId", "Status")
                        .HasDatabaseName("IX_InventoryLots_ItemLocationStatus");

                    b.ToTable("InventoryLots", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryLots_PurchasedHasSupplier", "\"SourceType\" <> 'Purchased' OR \"SupplierId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_InventoryLots_QuantityReceived_Positive", "\"QuantityReceived\" > 0");

                            t.HasCheckConstraint("CK_InventoryLots_QuantityRemaining_NotNegative", "\"QuantityRemaining\" >= 0");

                            t.HasCheckConstraint("CK_InventoryLots_QuantityRemaining_WithinReceived", "\"QuantityRemaining\" <= \"QuantityReceived\"");
                        });
                });

            modelBuilder.Entity("Domains.Entities.InventoryMovementLog", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovementId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ChangeQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovementId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.ToTable("InventoryMovementLogs");
                });

            modelBuilder.Entity("Domains.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxStockLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("StockUomId")
                        .HasColumnType("integer");

                    b.Property<int>("UomId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StockUomId");

                    b.HasIndex("UomId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Domains.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemLocation")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationType")
                        .IsUnique()
                        .HasDatabaseName("IX_Locations_SystemRole")
                        .HasFilter("\"IsSystemLocation\" = true AND \"LocationType\" <> 'In Transit'");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domains.Entities.ProductionBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<decimal>("ActualQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("AssignedCook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BatchMultiplier")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("EstimatedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProductionBatches");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PoId"));

                    b.Property<DateTime>("ExpectedArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProofImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QaInspectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QaNotes")
                        .HasColumnType("text");

                    b.Property<string>("QaStatus")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("PoId");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<int>("PoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PoItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PoItemQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int?>("PurchaseOrderPoId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseUomId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("PoItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseOrderPoId");

                    b.HasIndex("PurchaseUomId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseRequisition", b =>
                {
                    b.Property<int>("PrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedTotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("GeneratedPoNumbers")
                        .HasColumnType("text");

                    b.Property<string>("PrNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PrId");

                    b.HasIndex("PrNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchaseRequisitions_PrNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PurchaseRequisitions_Status");

                    b.ToTable("PurchaseRequisitions");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseRequisitionItem", b =>
                {
                    b.Property<int>("PrItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrItemId"));

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PrId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseUomId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int?>("SuggestedSupplierId")
                        .HasColumnType("integer");

                    b.HasKey("PrItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PrId");

                    b.HasIndex("PurchaseUomId");

                    b.HasIndex("SuggestedSupplierId");

                    b.ToTable("PurchaseRequisitionItems");
                });

            modelBuilder.Entity("Domains.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OutputQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecipeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Domains.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StandardQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("UomId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UomId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Domains.Entities.StockLedger", b =>
                {
                    b.Property<long>("LedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LedgerId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("LotId")
                        .HasColumnType("integer");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ReversalOfLedgerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("UomId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LedgerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("LotId")
                        .HasDatabaseName("IX_StockLedgers_LotId");

                    b.HasIndex("ReversalOfLedgerId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockLedgers_ReversalOf")
                        .HasFilter("\"ReversalOfLedgerId\" IS NOT NULL");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("IX_StockLedgers_Reference");

                    b.HasIndex("ItemId", "LocationId", "PostedAt")
                        .HasDatabaseName("IX_StockLedgers_ItemLocationPostedAt");

                    b.ToTable("StockLedgers", t =>
                        {
                            t.HasCheckConstraint("CK_StockLedgers_Quantity_NonZero", "\"Quantity\" <> 0");
                        });
                });

            modelBuilder.Entity("Domains.Entities.StockTransfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransferId"));

                    b.Property<int>("DestLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TransferQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("TransferId");

                    b.HasIndex("DestLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("Domains.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Domains.Entities.SupplierDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_SupplierDocuments_ExpiryDate");

                    b.HasIndex("SupplierId", "DocumentType")
                        .HasDatabaseName("IX_SupplierDocuments_Supplier_Type");

                    b.ToTable("SupplierDocuments");
                });

            modelBuilder.Entity("Domains.Entities.SupplierItem", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinOrderQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("PackSize")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("PurchaseUomId")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierItemName")
                        .HasColumnType("text");

                    b.Property<string>("SupplierSku")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("SupplierId", "ItemId");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_SupplierItems_ItemId");

                    b.HasIndex("PurchaseUomId");

                    b.ToTable("SupplierItems", t =>
                        {
                            t.HasCheckConstraint("CK_SupplierItems_MinOrderQuantity_Positive", "\"MinOrderQuantity\" > 0");

                            t.HasCheckConstraint("CK_SupplierItems_PackSize_Positive", "\"PackSize\" > 0");

                            t.HasCheckConstraint("CK_SupplierItems_UnitPrice_Positive", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("Domains.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UomId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BaseUomId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UomId");

                    b.HasIndex("BaseUomId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("Domains.Entities.BatchConsumption", b =>
                {
                    b.HasOne("Domains.Entities.ProductionBatch", "Batch")
                        .WithMany("BatchConsumptions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("BatchConsumptions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Supplier", "SourceSupplier")
                        .WithMany("SourcedBatchConsumptions")
                        .HasForeignKey("SourceSupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Item");

                    b.Navigation("SourceSupplier");
                });

            modelBuilder.Entity("Domains.Entities.FinishedProduct", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("FinishedProducts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domains.Entities.Inventory", b =>
                {
                    b.HasOne("Domains.Entities.Driver", "Driver")
                        .WithMany("Inventories")
                        .HasForeignKey("DriverId");

                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domains.Entities.InventoryLot", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domains.Entities.UnitOfMeasure", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("Supplier");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Domains.Entities.InventoryMovementLog", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("InventoryMovementLogs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Location", "Location")
                        .WithMany("InventoryMovementLogs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domains.Entities.Item", b =>
                {
                    b.HasOne("Domains.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.UnitOfMeasure", "StockUom")
                        .WithMany()
                        .HasForeignKey("StockUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.UnitOfMeasure", "Uom")
                        .WithMany("Items")
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("StockUom");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Domains.Entities.Location", b =>
                {
                    b.HasOne("Domains.Entities.Location", "ParentLocation")
                        .WithMany()
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("Domains.Entities.ProductionBatch", b =>
                {
                    b.HasOne("Domains.Entities.FinishedProduct", "Product")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Recipe", "Recipe")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Domains.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PurchaseOrderPoId");

                    b.HasOne("Domains.Entities.UnitOfMeasure", "PurchaseUom")
                        .WithMany()
                        .HasForeignKey("PurchaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("PurchaseUom");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseRequisitionItem", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.PurchaseRequisition", "PurchaseRequisition")
                        .WithMany("Items")
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.UnitOfMeasure", "PurchaseUom")
                        .WithMany()
                        .HasForeignKey("PurchaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Supplier", "SuggestedSupplier")
                        .WithMany()
                        .HasForeignKey("SuggestedSupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("PurchaseRequisition");

                    b.Navigation("PurchaseUom");

                    b.Navigation("SuggestedSupplier");
                });

            modelBuilder.Entity("Domains.Entities.Recipe", b =>
                {
                    b.HasOne("Domains.Entities.FinishedProduct", "Product")
                        .WithMany("Recipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domains.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.UnitOfMeasure", "Uom")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Domains.Entities.StockLedger", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.InventoryLot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.StockLedger", "ReversalOf")
                        .WithMany()
                        .HasForeignKey("ReversalOfLedgerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("Lot");

                    b.Navigation("ReversalOf");
                });

            modelBuilder.Entity("Domains.Entities.StockTransfer", b =>
                {
                    b.HasOne("Domains.Entities.Location", "DestLocation")
                        .WithMany()
                        .HasForeignKey("DestLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.FinishedProduct", "Product")
                        .WithMany("StockTransfers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestLocation");

                    b.Navigation("Product");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("Domains.Entities.SupplierDocument", b =>
                {
                    b.HasOne("Domains.Entities.Supplier", "Supplier")
                        .WithMany("SupplierDocuments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domains.Entities.SupplierItem", b =>
                {
                    b.HasOne("Domains.Entities.Item", "Item")
                        .WithMany("SupplierItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.UnitOfMeasure", "PurchaseUom")
                        .WithMany()
                        .HasForeignKey("PurchaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domains.Entities.Supplier", "Supplier")
                        .WithMany("SupplierItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseUom");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domains.Entities.UnitOfMeasure", b =>
                {
                    b.HasOne("Domains.Entities.UnitOfMeasure", "BaseUom")
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUom");
                });

            modelBuilder.Entity("Domains.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domains.Entities.Driver", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Domains.Entities.FinishedProduct", b =>
                {
                    b.Navigation("ProductionBatches");

                    b.Navigation("Recipes");

                    b.Navigation("StockTransfers");
                });

            modelBuilder.Entity("Domains.Entities.Item", b =>
                {
                    b.Navigation("BatchConsumptions");

                    b.Navigation("FinishedProducts");

                    b.Navigation("Inventories");

                    b.Navigation("InventoryMovementLogs");

                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("SupplierItems");
                });

            modelBuilder.Entity("Domains.Entities.Location", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryMovementLogs");
                });

            modelBuilder.Entity("Domains.Entities.ProductionBatch", b =>
                {
                    b.Navigation("BatchConsumptions");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("Domains.Entities.PurchaseRequisition", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domains.Entities.Recipe", b =>
                {
                    b.Navigation("ProductionBatches");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Domains.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SourcedBatchConsumptions");

                    b.Navigation("SupplierDocuments");

                    b.Navigation("SupplierItems");
                });

            modelBuilder.Entity("Domains.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
